export const content = `# Recall (Suspend Bill)

## 📝 Description
The **Recall** function allows staff to reopen a previously suspended bill so that billing can continue without re-entering items.

---

## 🎯 Purpose
- To **recall suspended bills** and continue processing them.  
- Useful when a transaction was put on hold (e.g., customer needed time to decide or fetch payment).  

---

## 📋 Steps
- **STEP-01:** Scan the **suspended bill** barcode **OR** enter the **Suspend Serial No**.  
  - Format: \`mmdd0001\` (Example: \`01120001\`)  
- **STEP-02:** Press the **RECALL key** on the POS.  

---

## ✅ Expected Result
- The suspended bill will be displayed on the POS screen.  
- Staff can continue billing from where it was left off.  

---

## 💡 Notes
- A **Suspend Bill Recall Report** can be generated by selecting *Suspend Bill Recall Report* from the menu.  
`;